# Generated by Django 5.0.1 on 2024-01-18 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название категории')),
                ('description', models.TextField(verbose_name='описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='логотип')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_id', models.CharField(max_length=100, unique=True, verbose_name='помещение')),
                ('floor', models.IntegerField(verbose_name='этаж')),
                ('sq_m', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='площадь')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='offices/', verbose_name='фото')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='offices/', verbose_name='фото')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='offices/', verbose_name='фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ('office_id',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='дата')),
                ('duration', models.IntegerField(choices=[(0, '09:00 – 18:00'), (1, '9:00 – 13:00'), (2, '13:00 – 18:00')], verbose_name='длительность')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='арендатор')),
            ],
            options={
                'verbose_name': 'Бронь переговорки',
                'verbose_name_plural': 'Брони переговорки',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=100, unique=True, verbose_name='номер авто')),
                ('model', models.CharField(max_length=100, verbose_name='модель')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='арендатор')),
            ],
            options={
                'verbose_name': 'Допуск авто',
                'verbose_name_plural': 'Допуски авто',
            },
        ),
        migrations.CreateModel(
            name='User_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='дата и время заявки')),
                ('office_id', models.CharField(max_length=100, verbose_name='помещение')),
                ('description', models.TextField(verbose_name='описание')),
                ('urgency', models.CharField(choices=[('срочно', 'срочно'), ('в текущем режиме', 'в текущем режиме')], default='в текущем режиме', max_length=20, verbose_name='срочность')),
                ('status', models.CharField(choices=[('выполнено', 'выполнено'), ('в работе', 'в работе')], default='в работе', max_length=20, verbose_name='статус')),
                ('comments', models.TextField(verbose_name='комментарий')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('date',),
            },
        ),
    ]
